import type { EditFormData } from "./EditForm";
import { 
  Camera, Sun, Palette, Sparkles, CloudRain, Star, 
  Zap, Heart, Crown, Mountain, Building, Flame,
  Ghost, Snowflake, Music, Glasses, Brush, Skull,
  Umbrella, Trees, Sunset, Moon, Waves, Wind,
  BookOpen, Gem, Swords, Shirt
} from "lucide-react";

interface Template {
  id: string;
  label: string;
  description: string;
  icon: typeof Camera;
  data: Partial<EditFormData>;
}

const templates: Template[] = [
  {
    id: "editorial_magazine",
    label: "Editorial de Revista",
    description: "Look de capa de revista com iluminação profissional",
    icon: Crown,
    data: {
      changes: "Aplicar tratamento editorial de alta moda, pele impecável com textura natural, iluminação de estúdio sofisticada",
      preserve: "Rosto, identidade, formato dos olhos, estrutura facial",
      style: "editorial",
      lighting: "studio",
      lightingDirection: "butterfly",
      realism: "high",
      colorTone: "natural",
      mood: "powerful",
      skinTexture: "dewy",
      expression: "confident",
      cameraLens: "85mm",
      depth: "shallow",
      postProcessing: ["sharpening", "color_grade"],
      intensity: "moderate",
      makeup: "glamorous",
    },
  },
  {
    id: "golden_hour_dreamy",
    label: "Golden Hour Sonhador",
    description: "Luz dourada mágica com atmosfera etérea",
    icon: Sun,
    data: {
      changes: "Adicionar iluminação golden hour, brilho dourado na pele, raios de sol suaves, atmosfera mágica e quente",
      preserve: "Rosto, identidade, posição do corpo",
      style: "ethereal",
      lighting: "golden_hour",
      lightingDirection: "back",
      realism: "high",
      colorTone: "warm_gold",
      mood: "dreamy",
      skinTexture: "dewy",
      timeOfDay: "golden",
      weather: "clear",
      depth: "shallow",
      postProcessing: ["bokeh", "lens_flare", "color_grade"],
      intensity: "moderate",
    },
  },
  {
    id: "cinematic_dramatic",
    label: "Cinematográfico Dramático",
    description: "Estilo de filme com alto contraste e sombras intensas",
    icon: Flame,
    data: {
      changes: "Aplicar look cinematográfico com contraste dramático, sombras profundas, color grading de filme",
      preserve: "Rosto, identidade, expressão facial",
      style: "cinematic",
      lighting: "dramatic",
      lightingDirection: "rembrandt",
      realism: "high",
      colorTone: "teal_orange",
      mood: "mysterious",
      skinTexture: "natural",
      depth: "moderate",
      postProcessing: ["grain", "vignette", "color_grade"],
      intensity: "strong",
      shadowStyle: "dramatic_shadow",
    },
  },
  {
    id: "clean_studio",
    label: "Estúdio Profissional",
    description: "Fundo limpo com iluminação de estúdio perfeita",
    icon: Camera,
    data: {
      changes: "Trocar fundo para estúdio branco clean, iluminação profissional de três pontos, retoque sutil",
      preserve: "Rosto, identidade, roupas, acessórios",
      style: "realistic",
      lighting: "studio",
      lightingDirection: "loop",
      realism: "ultra",
      background: "studio_white",
      colorTone: "natural",
      mood: "calm",
      skinTexture: "smooth",
      cameraLens: "85mm",
      depth: "moderate",
      environment: "studio",
      postProcessing: ["sharpening"],
      intensity: "moderate",
    },
  },
  {
    id: "vintage_retro",
    label: "Vintage Retrô",
    description: "Estética analógica com tons quentes e granulação",
    icon: Palette,
    data: {
      changes: "Aplicar estética de filme analógico vintage, tons desbotados, leve granulação, cores quentes suaves",
      preserve: "Rosto, identidade, composição geral",
      style: "vintage",
      lighting: "soft",
      realism: "medium",
      colorTone: "sepia",
      mood: "nostalgic",
      skinTexture: "natural",
      postProcessing: ["grain", "vignette", "chromatic", "light_leaks"],
      filmStock: "portra_400",
      intensity: "moderate",
    },
  },
  {
    id: "noir_mystery",
    label: "Film Noir",
    description: "Preto e branco dramático com sombras intensas",
    icon: Star,
    data: {
      changes: "Converter para estética film noir, alto contraste preto e branco, sombras marcantes, atmosfera de mistério",
      preserve: "Rosto, identidade, posição",
      style: "noir",
      lighting: "hard",
      lightingDirection: "split",
      realism: "high",
      colorTone: "bw",
      mood: "mysterious",
      skinTexture: "matte",
      expression: "mysterious",
      postProcessing: ["grain", "vignette", "sharpening"],
      shadowStyle: "hard_shadow",
      intensity: "strong",
    },
  },
  {
    id: "romantic_soft",
    label: "Romântico Suave",
    description: "Tons pastéis com luz suave e atmosfera íntima",
    icon: Heart,
    data: {
      changes: "Aplicar atmosfera romântica, luz suave difusa, tons rosados e pastéis, brilho delicado na pele",
      preserve: "Rosto, identidade, expressão",
      style: "ethereal",
      lighting: "soft",
      lightingDirection: "front",
      realism: "high",
      colorTone: "pastel",
      mood: "romantic",
      skinTexture: "porcelain",
      depth: "very_shallow",
      postProcessing: ["bokeh", "color_grade", "glow"],
      lightColor: "pink_light",
      intensity: "moderate",
    },
  },
  {
    id: "urban_street",
    label: "Street / Urbano",
    description: "Vibe urbana com cenário de cidade e luz natural",
    icon: Building,
    data: {
      changes: "Ambientação urbana street style, luz natural da cidade, cores vibrantes, energia metropolitana",
      preserve: "Rosto, identidade, roupas",
      style: "documentary",
      lighting: "natural",
      realism: "high",
      colorTone: "vibrant",
      mood: "energetic",
      background: "urban",
      environment: "city",
      skinTexture: "natural",
      cameraLens: "35mm",
      depth: "moderate",
      postProcessing: ["sharpening", "color_grade"],
      intensity: "moderate",
    },
  },
  {
    id: "nature_outdoor",
    label: "Natureza / Outdoor",
    description: "Cenário natural com iluminação orgânica",
    icon: Mountain,
    data: {
      changes: "Ambientação em cenário natural, luz do dia filtrada por árvores, tons verdes e terrosos, ar fresco",
      preserve: "Rosto, identidade",
      style: "realistic",
      lighting: "natural",
      realism: "high",
      colorTone: "natural",
      mood: "calm",
      background: "nature",
      environment: "forest",
      weather: "clear",
      timeOfDay: "morning",
      skinTexture: "natural",
      depth: "shallow",
      postProcessing: ["bokeh", "color_grade"],
      season: "spring",
      intensity: "moderate",
    },
  },
  {
    id: "neon_cyberpunk",
    label: "Neon / Cyberpunk",
    description: "Luzes neon vibrantes com atmosfera futurista",
    icon: Zap,
    data: {
      changes: "Iluminação neon colorida, reflexos de luz roxa e azul na pele, atmosfera cyberpunk, cidade noturna futurista",
      preserve: "Rosto, identidade, formato do corpo",
      style: "cyberpunk",
      lighting: "neon",
      lightingDirection: "side",
      realism: "high",
      colorTone: "neon_colors",
      mood: "edgy",
      environment: "neon_city",
      timeOfDay: "night",
      skinTexture: "dewy",
      depth: "shallow",
      postProcessing: ["chromatic", "color_grade", "sharpening"],
      lightColor: "mixed_light",
      intensity: "strong",
    },
  },
  {
    id: "rainy_moody",
    label: "Chuvoso / Melancólico",
    description: "Chuva, reflexos e atmosfera cinematográfica",
    icon: CloudRain,
    data: {
      changes: "Adicionar chuva caindo, reflexos no chão molhado, gotículas de água, atmosfera melancólica cinematográfica",
      preserve: "Rosto, identidade, roupas",
      style: "cinematic",
      lighting: "overcast",
      realism: "ultra",
      colorTone: "desaturated",
      mood: "melancholic",
      weather: "rainy",
      environment: "outdoor",
      skinTexture: "wet",
      postProcessing: ["grain", "vignette", "color_grade", "reflection"],
      intensity: "strong",
    },
  },
  {
    id: "glamour_luxury",
    label: "Glamour / Luxo",
    description: "Estilo Hollywood com brilho e elegância",
    icon: Sparkles,
    data: {
      changes: "Look de glamour luxuoso, iluminação perfeita de Hollywood, pele radiante, brilho dourado sutil",
      preserve: "Rosto, identidade, proporções",
      style: "glamour",
      lighting: "studio",
      lightingDirection: "butterfly",
      realism: "hyper",
      colorTone: "warm_gold",
      mood: "sophisticated",
      skinTexture: "porcelain",
      expression: "confident",
      cameraLens: "85mm",
      depth: "shallow",
      postProcessing: ["sharpening", "color_grade", "bokeh"],
      makeup: "glamorous",
      intensity: "moderate",
    },
  },
  // NEW TEMPLATES
  {
    id: "kodak_portra",
    label: "Kodak Portra 400",
    description: "Simulação de filme Kodak Portra com tons suaves",
    icon: Palette,
    data: {
      changes: "Aplicar estética de filme Kodak Portra 400, tons de pele quentes e suaves, granulação fina, cores pastéis naturais",
      preserve: "Rosto, identidade, composição",
      style: "realistic",
      lighting: "natural",
      realism: "high",
      colorTone: "warm_orange",
      mood: "nostalgic",
      skinTexture: "natural",
      filmStock: "portra_400",
      postProcessing: ["grain", "color_grade"],
      intensity: "moderate",
    },
  },
  {
    id: "cinestill_night",
    label: "CineStill 800T Noturno",
    description: "Film look noturno com halation e tons quentes",
    icon: Moon,
    data: {
      changes: "Aplicar look CineStill 800T, halation vermelho ao redor das luzes, tons tungstênio, atmosfera noturna cinematográfica",
      preserve: "Rosto, identidade",
      style: "cinematic",
      lighting: "neon",
      realism: "high",
      colorTone: "warm_orange",
      mood: "mysterious",
      timeOfDay: "night",
      filmStock: "cinestill_800t",
      postProcessing: ["halation", "grain", "color_grade"],
      intensity: "strong",
    },
  },
  {
    id: "dark_academia",
    label: "Dark Academia",
    description: "Atmosfera acadêmica com tons quentes e livros",
    icon: BookOpen,
    data: {
      changes: "Ambiente dark academia, iluminação quente de lamparina, tons marrons e dourados, atmosfera intelectual e misteriosa",
      preserve: "Rosto, identidade",
      style: "dark_academia",
      lighting: "candlelight",
      realism: "high",
      colorTone: "earth_tones",
      mood: "mysterious",
      environment: "library",
      skinTexture: "natural",
      postProcessing: ["vignette", "color_grade", "grain"],
      lightColor: "warm_light",
      season: "autumn",
      intensity: "moderate",
    },
  },
  {
    id: "vaporwave_retro",
    label: "Vaporwave / Retrowave",
    description: "Estética anos 90 com rosa, cyan e glitch",
    icon: Waves,
    data: {
      changes: "Aplicar estética vaporwave, cores rosa e cyan, efeitos digitais retrô, atmosfera nostálgica dos anos 90",
      preserve: "Rosto, identidade",
      style: "vaporwave",
      lighting: "neon",
      realism: "stylized",
      colorTone: "neon_colors",
      mood: "dreamy",
      postProcessing: ["chromatic", "color_grade", "duotone"],
      lightColor: "pink_light",
      intensity: "strong",
    },
  },
  {
    id: "steampunk_victorian",
    label: "Steampunk Vitoriano",
    description: "Estética industrial vitoriana com engrenagens",
    icon: Glasses,
    data: {
      changes: "Aplicar estética steampunk, elementos vitorianos industriais, tons de bronze e cobre, engrenagens e vapor",
      preserve: "Rosto, identidade",
      style: "steampunk",
      lighting: "candlelight",
      realism: "high",
      colorTone: "warm_gold",
      mood: "mysterious",
      postProcessing: ["vignette", "color_grade", "grain"],
      lightColor: "warm_light",
      intensity: "strong",
    },
  },
  {
    id: "underwater_dream",
    label: "Subaquático Onírico",
    description: "Cena debaixo d'água com luz etérea",
    icon: Waves,
    data: {
      changes: "Criar atmosfera subaquática, luz filtrada pela água, bolhas flutuantes, cabelo esvoaçante, tons azul-esverdeados",
      preserve: "Rosto, identidade",
      style: "ethereal",
      lighting: "underwater_light",
      realism: "high",
      colorTone: "cool_blue",
      mood: "dreamy",
      environment: "underwater",
      skinTexture: "wet",
      postProcessing: ["glow", "color_grade", "dust_particles"],
      intensity: "strong",
    },
  },
  {
    id: "oil_painting_classic",
    label: "Pintura a Óleo Clássica",
    description: "Transformação em pintura renascentista",
    icon: Brush,
    data: {
      changes: "Transformar em pintura a óleo clássica renascentista, pinceladas visíveis, cores ricas e profundas, digno de museu",
      preserve: "Rosto, identidade, proporções",
      style: "oil_painting",
      lighting: "dramatic",
      lightingDirection: "rembrandt",
      realism: "stylized",
      colorTone: "warm_gold",
      mood: "powerful",
      artMedium: "oil_canvas",
      postProcessing: ["vignette"],
      intensity: "extreme",
    },
  },
  {
    id: "anime_manga",
    label: "Anime / Manga",
    description: "Estilo de animação japonesa vibrante",
    icon: Star,
    data: {
      changes: "Converter para estilo anime/manga, cel shading, olhos grandes expressivos, cores vibrantes, linhas limpas",
      preserve: "Identidade geral, pose, roupas",
      style: "anime",
      realism: "cartoon",
      colorTone: "vibrant",
      mood: "energetic",
      skinTexture: "smooth",
      postProcessing: ["sharpening"],
      intensity: "extreme",
    },
  },
  {
    id: "gothic_dark",
    label: "Gótico / Dark",
    description: "Atmosfera sombria com elementos góticos",
    icon: Skull,
    data: {
      changes: "Aplicar estética gótica, sombras profundas, tons escuros, atmosfera sinistra e elegante, arquitetura ornamentada",
      preserve: "Rosto, identidade",
      style: "gothic",
      lighting: "dramatic",
      lightingDirection: "side",
      realism: "high",
      colorTone: "moody",
      mood: "dark",
      skinTexture: "porcelain",
      expression: "mysterious",
      postProcessing: ["vignette", "color_grade", "grain"],
      shadowStyle: "dramatic_shadow",
      makeup: "gothic",
      intensity: "strong",
    },
  },
  {
    id: "cottagecore_pastoral",
    label: "Cottagecore Pastoral",
    description: "Cenário campestre com flores e luz suave",
    icon: Trees,
    data: {
      changes: "Cenário cottagecore pastoral, flores silvestres, luz suave da manhã, atmosfera bucólica e acolhedora, cores quentes naturais",
      preserve: "Rosto, identidade",
      style: "cottagecore",
      lighting: "soft",
      realism: "high",
      colorTone: "pastel",
      mood: "calm",
      environment: "garden",
      weather: "clear",
      timeOfDay: "morning",
      skinTexture: "natural",
      postProcessing: ["bokeh", "color_grade", "glow"],
      season: "spring",
      intensity: "moderate",
    },
  },
  {
    id: "concert_stage",
    label: "Palco / Show",
    description: "Iluminação de concerto com energia vibrante",
    icon: Music,
    data: {
      changes: "Iluminação de palco de show, lasers coloridos, fumaça atmosférica, energia de concerto, multidão ao fundo",
      preserve: "Rosto, identidade",
      style: "dramatic",
      lighting: "neon",
      realism: "high",
      colorTone: "vibrant",
      mood: "euphoric",
      environment: "concert",
      timeOfDay: "night",
      postProcessing: ["lens_flare", "smoke", "color_grade"],
      lightColor: "mixed_light",
      intensity: "strong",
    },
  },
  {
    id: "snowy_winter",
    label: "Inverno Nevado",
    description: "Cenário de neve com atmosfera gelada",
    icon: Snowflake,
    data: {
      changes: "Cenário de inverno com neve caindo, frost nos cílios e cabelo, bafo visível, atmosfera gelada e mágica",
      preserve: "Rosto, identidade",
      style: "cinematic",
      lighting: "overcast",
      realism: "ultra",
      colorTone: "cool_blue",
      mood: "calm",
      environment: "snow",
      weather: "snowy",
      season: "winter",
      skinTexture: "natural",
      postProcessing: ["bokeh", "color_grade", "dust_particles"],
      intensity: "strong",
    },
  },
  {
    id: "sunset_beach",
    label: "Pôr do Sol na Praia",
    description: "Silhueta dourada com ondas e céu colorido",
    icon: Sunset,
    data: {
      changes: "Pôr do sol na praia, silhueta dourada, céu laranja e roxo, reflexo na água, areia molhada, atmosfera mágica",
      preserve: "Rosto, identidade, silhueta",
      style: "cinematic",
      lighting: "golden_hour",
      lightingDirection: "back",
      realism: "high",
      colorTone: "warm_orange",
      mood: "romantic",
      environment: "beach",
      timeOfDay: "sunset",
      weather: "clear",
      postProcessing: ["lens_flare", "color_grade", "bokeh"],
      season: "summer",
      intensity: "moderate",
    },
  },
  {
    id: "3d_render_modern",
    label: "3D Render Moderno",
    description: "Estilo CGI com iluminação volumétrica",
    icon: Gem,
    data: {
      changes: "Converter para estilo 3D render moderno, iluminação volumétrica, ray tracing, superfícies polidas, qualidade Pixar/Unreal",
      preserve: "Identidade, proporções gerais",
      style: "3d_render",
      lighting: "studio",
      realism: "stylized",
      colorTone: "vibrant",
      mood: "playful",
      artMedium: "3d_render",
      skinTexture: "smooth",
      postProcessing: ["sharpening", "hdr"],
      intensity: "extreme",
    },
  },
  {
    id: "fashion_editorial",
    label: "Fashion Editorial Avant-Garde",
    description: "Alta moda com maquiagem artística e poses ousadas",
    icon: Shirt,
    data: {
      changes: "Transformar em editorial de alta moda avant-garde, maquiagem artística, iluminação experimental, pose editorial ousada",
      preserve: "Rosto, identidade",
      style: "fashion",
      lighting: "studio",
      lightingDirection: "side",
      realism: "high",
      colorTone: "high_contrast",
      mood: "rebellious",
      skinTexture: "matte",
      expression: "fierce",
      pose: "editorial",
      makeup: "avant_garde",
      cameraLens: "85mm",
      depth: "shallow",
      postProcessing: ["sharpening", "color_grade"],
      intensity: "strong",
    },
  },
  {
    id: "fantasy_epic",
    label: "Fantasia Épica",
    description: "Cenário mágico com iluminação encantada",
    icon: Swords,
    data: {
      changes: "Cenário de fantasia épica, elementos mágicos, iluminação encantada, partículas brilhantes flutuantes, atmosfera de outro mundo",
      preserve: "Rosto, identidade",
      style: "fantasy",
      lighting: "volumetric",
      realism: "high",
      colorTone: "jewel_tones",
      mood: "epic",
      environment: "castle",
      postProcessing: ["glow", "sparkles", "color_grade", "dust_particles"],
      lightColor: "purple_light",
      intensity: "strong",
    },
  },
  {
    id: "polaroid_instant",
    label: "Polaroid Instantâneo",
    description: "Estética de foto instantânea com cores desbotadas",
    icon: Camera,
    data: {
      changes: "Aplicar estética de Polaroid instantâneo, cores levemente desbotadas, borda branca, look vintage casual",
      preserve: "Rosto, identidade, momento",
      style: "vintage",
      lighting: "natural",
      realism: "medium",
      colorTone: "muted",
      mood: "nostalgic",
      filmStock: "polaroid",
      postProcessing: ["grain", "vignette", "light_leaks"],
      intensity: "moderate",
      aspectRatio: "1:1",
    },
  },
];

interface TemplatePresetsProps {
  onApply: (data: Partial<EditFormData>) => void;
}

const TemplatePresets = ({ onApply }: TemplatePresetsProps) => {
  return (
    <div className="space-y-4">
      <div className="flex items-center gap-3 mb-2">
        <div className="w-2 h-2 rounded-full bg-primary" />
        <h3 className="text-xs font-extrabold uppercase tracking-wider text-primary">
          Modelos Pré-Prontos ({templates.length})
        </h3>
        <div className="flex-1 h-px bg-secondary" />
      </div>
      <p className="text-[11px] text-muted-foreground">
        Clique em um modelo para preencher automaticamente. Depois personalize como quiser.
      </p>
      <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
        {templates.map((t) => (
          <button
            key={t.id}
            onClick={() => onApply(t.data)}
            className="neo-button rounded-xl p-3.5 text-left transition-all duration-200 hover:-translate-y-0.5 group"
          >
            <div className="flex items-center gap-2 mb-1.5">
              <div className="w-7 h-7 rounded-lg neo-convex flex items-center justify-center group-hover:shadow-neo transition-all">
                <t.icon className="w-3.5 h-3.5 text-primary" />
              </div>
              <span className="text-xs font-bold text-foreground leading-tight">{t.label}</span>
            </div>
            <p className="text-[10px] text-muted-foreground leading-snug">{t.description}</p>
          </button>
        ))}
      </div>
    </div>
  );
};

export default TemplatePresets;
